name: local_database
description: A new Flutter package project.
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  shared_preferences:
  flutter_modular:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
