# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the develop branch
  push:
    branches: [ develop ]
  pull_request:
    branches: [ develop ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  Tests:
   runs-on: macos-latest
   steps:
    - uses: actions/checkout@v2
    - uses: subosito/flutter-action@v1
      with:
        flutter-version: '1.22.4'
    - run: flutter pub get
    - run: bash ./test_application.sh
    - uses: codecov/codecov-action@v1
      with:
        flags: unittests # optional
        name: codecov-umbrella # optional
        fail_ci_if_error: true # optional (default = false)
        verbose: true 
  # build-iOS:
  #  runs-on: macos-latest
  #  steps:
  #   - uses: actions/checkout@v2
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '1.22.4'
  #   - run: flutter pub get
  #   - run: flutter build ios --release --no-codesign
  # build-android:
  #  runs-on: macos-latest
  #  steps:
  #   - uses: actions/checkout@v2
  #   - uses: subosito/flutter-action@v1
  #     with:
  #       flutter-version: '1.22.4'
  #   - run: flutter pub get
  #   - run: flutter build apk
